quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:simplemq.db?busy_timeout=5000
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.dialect=org.hibernate.community.dialect.SQLiteDialect
quarkus.hibernate-orm.log.sql=true

# Cluster configuration
simplemq.cluster.node-id=${NODE_ID:node1}
simplemq.cluster.address=${NODE_ADDRESS:localhost:9851}
simplemq.cluster.peers=${CLUSTER_PEERS:node1=localhost:9851}

# Persistence configuration
simplemq.persistence.enabled=${SIMPLEMQ_PERSISTENCE_ENABLED:true}
